[WIP] Process RepoCred operation
redhat-appstudio/managed-gitops pull request #168
Opened 2022-06-30 15:33 UTC by drpaneas

#### Description:
- 

#### Link to JIRA Story (if applicable):

(https://issues.redhat.com/browse/GITOPSRVCE-108)

2022-07-14 15:25 UTC, jgwest requested changes
Looks great, thanks Panos! Just some minor tweaks, plus a rebase needed, then G2G!

2022-07-14 15:25 UTC, jgwest commented on cluster-agent/controllers/managed-gitops/eventloop/repocred.go
> +	const retry, noRetry = true, false
:tada:

2022-07-15 10:09 UTC, drpaneas commented on cluster-agent/controllers/managed-gitops/eventloop/repocred_test.go
> +			//It("If there is a valid Operation ID for a problematic ArgoCD secret, fix the secret", func() {
This commented section has to be removed, sorry I forgot about it (Goland IDE tends to auto-wrap big comment section, so I didn't spot this). This "it" it actually the Scenario 2 which is under test already, so all fine.

2022-07-18 08:36 UTC, drpaneas commented
/retest

2022-07-20 00:19 UTC, jgwest commented
/retest

2022-07-20 00:40 UTC, jgwest approved these changes
Looks great, thanks @drpaneas!

2022-07-20 00:40 UTC, merged