Garbage Collect completed/failed operations periodically
redhat-appstudio/managed-gitops pull request #172
Opened 2022-07-06 07:06 UTC by chetan-rns

#### Description:
- Added a new field `gc_expiration_time` that indicates the amount of time in seconds to wait before removing the operation from the DB.
- Added a goroutine that continuously garbage collects completed/failed operations periodically.
- Unit tests 
#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-174

2022-07-06 10:51 UTC, drpaneas commented on cluster-agent/controllers/managed-gitops/operation_controller_test.go
> +Copyright 2021.
```suggestion
Copyright 2022.
```

2022-07-13 07:40 UTC, jparsai approved these changes

2022-07-13 12:12 UTC, drpaneas reviewed
@chetan-rns great work here, very nice clean code and I was very happy to see the Gomega matcher pattern in use :D I left a minor comment for the unit-test and a question I have for what is the definition of garbage collected operation. For example, a garbage collected operation is considered as such when it's been deleted from both places (cluster + database) ? or just from the database? And a follow-up question would be, what happens to the the Operation CR that is deleted from the database but still presented on the cluster?

One proposal for this ^ scenario: If the deletion from the database succeeds, but the deletion from the cluster fails, then update the CR on the cluster with a new state `orphaned`. Then use [Kubernetes CronJob](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/) to run periodically on a given schedule and delete these orphaned operations.

2022-07-13 12:12 UTC, drpaneas commented on cluster-agent/controllers/managed-gitops/operation_controller.go
> +			log.Info("successfully garbage collected operation", "operation_id", operation.Operation_id)
If the operation CR fails to be deleted from the cluster, you will end up with two logs. One log msg saying there is an error and another one saying that the operation has been garbage collected. To me, a garbage collected operation means that's deleted from both places (db + cluster).

```suggestion
			err = g.k8sClient.Delete(ctx, operationCR)
			if err != nil {
				log.Error(err, "failed to delete operation from the cluster", "operation_id", operation.Operation_id)
			} else {
				log.Info("successfully garbage collected operation", "operation_id", operation.Operation_id)
			}
```

What happens to the Operation that is failed to be deleted from the cluster but it has successfully been deleted from the database?

2022-07-14 13:38 UTC, chetan-rns commented on backend-shared/config/db/operations_test.go
> +		By("operation in waiting state shouldn't be returned")
Agreed. I've added a check

2022-07-14 13:44 UTC, chetan-rns commented
I've updated the PR to use `TaskRetryLoop` where we retry until the Operation CR is removed from the cluster.

2022-07-18 09:43 UTC, chetan-rns commented
/retest

2022-07-20 20:16 UTC, jgwest requested changes
Looks great, thanks @chetan-rns! Some minor tweaks then good to go.

2022-07-25 06:18 UTC, chetan-rns commented on backend-shared/config/db/operations_test.go
> +		By("create a sample operation")
It makes sense to use `It(...)` here for individual cases. I've updated the unit test

2022-07-26 20:41 UTC, jgwest approved these changes
Looks great, thanks again @chetan-rns!

2022-07-26 20:41 UTC, merged