DB unit tests to guard against missing WHERE clauses of UPDATE/DELETE operations
redhat-appstudio/managed-gitops pull request #174
Opened 2022-07-06 09:07 UTC by raghavi101

#### Description:
Create database unit tests which guard against missing WHERE clauses of UPDATE/DELETE operations to the database (causing a global delete)
- The tests are added to one singular file called `guardrow_test.go` within `backend-shared/config/db` so that it's easy to test and does not come in the way of other unit tests of database operations.
#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-173

2022-07-06 09:55 UTC, raghavi101 commented
/retest

2022-07-06 09:56 UTC, raghavi101 commented
/ retest

2022-07-19 11:57 UTC, drpaneas approved these changes
Technically, the testing coverage is sufficient. :D :D 

However the structure of the tests can be broken down to further individual parts (e.g. clear separation of pre-conditions, actions, and post-conditions). 

With Ginkgo's DSL (expressive Domain-Specific Language (DSL)) you can use nestable [`Describe`, `Context` and `When` container nodes](https://onsi.github.io/ginkgo/#organizing-specs-with-container-nodes) to help you organize your specs.  [`BeforeEach` and `AfterEach` setup nodes](https://onsi.github.io/ginkgo/#extracting-common-setup-beforeeach) for setup and cleanup.  [`It` and `Specify` subject nodes](https://onsi.github.io/ginkgo/#spec-subjects-it) that hold your assertions. [`BeforeSuite` and `AfterSuite` nodes](https://onsi.github.io/ginkgo/#suite-setup-and-cleanup-beforesuite-and-aftersuite) to prep for and cleanup after a suite... and [much more!](https://onsi.github.io/ginkgo/#writing-specs).

I am going to give /lgtm on this since we haven't agreed on team level about this yet, but we should consider it.

/lgtm

2022-07-20 21:00 UTC, jgwest requested changes
Looks great, thanks @raghavi101! Some minor tweaks below then good to go. 

One final note:
- For variable naming, you may want to use this format (for example, for cluster credentials):  
    - `clustercredentialsFirst/clustercredentialSecond` (cluster credentials all lowercase, then the second word as uppercase)
    - Or `clusterCredentialsFirst/clusterCredentialSecond` E.g. using camelcase for each word. 

This is more consistent with the format we are using elsewhere in the code.

2022-07-20 21:00 UTC, jgwest commented on backend-shared/config/db/guardrow_test.go
> +			Expect(applicationStatesecond.Sync_Status).Should(Equal("Sync"))
You will need to do a dbq.GetApplicationState() here, before doing the comparison, to make sure the `applicationStatesecond` object has been updated with the database. (The go object doesn't get updated automatically)

2022-07-20 21:00 UTC, jgwest commented on backend-shared/config/db/guardrow_test.go
> +			Expect(applicationsecond.Name).Should(Equal("test-application-update"))
Need to do a `dbq.GetApplication` for both first and second here, to ensure they have been updated with the new state of the database: as the Go objects won't be updated automatically (by the go-pg library we use).

2022-07-20 21:00 UTC, jgwest commented on backend-shared/config/db/guardrow_test.go
> +			Expect(operationsecond.Resource_id).Should(Equal("test-fake-resource-id-update"))
Need to go GetOperation here, for both operationFirst and operationSecond, to make sure that the Go object is up-to-date with the latest state of the database (it is not updated automatically.)

2022-07-20 21:00 UTC, jgwest commented on backend-shared/config/db/guardrow_test.go
> +	db "github.com/redhat-appstudio/managed-gitops/backend-shared/config/db"
The `db` part of the line, on the left, can be removed, as Go will automatically use the `db` package name from the right-most part of the package.

2022-07-20 21:00 UTC, jgwest commented on backend-shared/config/db/guardrow_test.go
> +var _ = Describe("GuardRow test", func() {
Can change 'guardrow test' to something like 'verify update/delete operations are not globally scoped'

2022-07-25 15:31 UTC, jgwest requested changes
Review comment changes look good, thanks @raghavi101! One more thing I happened to notice will verifying the changes from previous review.. it looks like we don't have tests for these scenarios:
- UpdateManagedEnvironment	
- UpdateRepositoryCredentials
- DeleteRepositoryCredentials

2022-07-29 15:14 UTC, jgwest approved these changes
LGTM, thanks again @raghavi101!

2022-07-29 15:14 UTC, merged