Add support for DeploymentTargetClaim in the Environment controller
redhat-appstudio/managed-gitops pull request #402
Opened 2023-03-29 06:05 UTC by chetan-rns

#### Description:
- Environment reconciler should use the secrets specified in the DeploymentTarget
- Reconciler should update the managed environment details if the DeploymentTarget is updated
- unit tests and e2e tests

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-388

2023-04-03 22:30 UTC, jgwest requested changes

2023-04-04 07:36 UTC, chetan-rns commented on appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
> +			Expect(err).ToNot(BeNil())
Here we are checking if the resource is not present and the error is not returned from the reconciler. So I suppose we don't have to change this

2023-04-04 07:36 UTC, chetan-rns commented on appstudio-controller/controllers/appstudio.redhat.com/environment_controller_test.go
> +			Expect(err).ToNot(BeNil())
Here we are checking if the resource is not present and the error is not returned from the reconciler. So I suppose we don't have to change this

2023-04-04 07:40 UTC, chetan-rns commented on appstudio-controller/controllers/appstudio.redhat.com/environment_controller.go
> +			builder.WithPredicates(predicate.GenerationChangedPredicate{}),
You are right. I just verified and it skipped the events with changes to the `status` field. I've replaced it with `ResourceVersionChangedPredicate`

2023-04-04 13:20 UTC, jgwest approved these changes
Looks great, thanks @chetan-rns!

2023-04-04 13:20 UTC, merged