Add PostgreSQL Data Source and Grafana dashboard (#491)
redhat-appstudio/managed-gitops pull request #417
Opened 2023-04-13 00:05 UTC by keithchong

#### Description:
- Sets up the dev env and in particular, the kube-auto target

#### Link to JIRA Story (if applicable):

See https://issues.redhat.com/browse/GITOPSRVCE-491

2023-04-18 01:12 UTC, jgwest requested changes

2023-04-18 20:56 UTC, keithchong commented on create-dev-env.sh
> +  psql -h localhost -p 5432 -U postgres -c 'ALTER SYSTEM SET shared_preload_libraries TO pg_stat_statements;' 1> /dev/null
It looks like the ./psql.sh script will work if you are running the db locally in a docker container.  This way is needed if the db is running on OpenShift in a pod.

Plus, I have psql set up on my PATH already.

2023-04-19 00:23 UTC, jgwest commented on create-dev-env.sh
> +  psql -h localhost -p 5432 -U postgres -c 'ALTER SYSTEM SET shared_preload_libraries TO pg_stat_statements;' 1> /dev/null
`psql.sh` should still work in this case. Correct me if I'm wrong, but the parameters you are passing to psql CLI are the same as we are specifying in `psql.sh`, e.g. localhost, on port 5432, etc.

2023-04-26 18:44 UTC, jgwest approved these changes
Looks great, the statistics that are output by this are really nice to have, thanks @keithchong!

2023-04-26 18:45 UTC, merged