Add tests to check the sanity for the database input methods
redhat-appstudio/managed-gitops pull request #47
Opened 2021-12-13 13:00 UTC by samyak-jn

Hi :hugs:

This pull request is in with regards to story GITOPS-1375, which checks for inputting malicious values within the database objects!

2021-12-13 23:37 UTC, jgwest requested changes
Looks good, minor tweak then good to go.

2021-12-13 23:37 UTC, jgwest commented on backend-shared/config/db/injection_test.go
> +	if err = dbq.CreateClusterCredentials(ctx, &clusterCredentials); err != nil {
These should all use this:
```
	if !assert.NoError(t, err) {
			return
		}
```
or at least `assert.NoError(t, err)`), even if this is already tested elsewhere.

2021-12-14 03:23 UTC, samyak-jn reviewed
Made the relevant changes (use of assert) where it was left, thanks!

2021-12-14 16:14 UTC, jgwest approved these changes
:sunglasses:

2021-12-14 16:14 UTC, merged