chore: E2E refactoring.
redhat-appstudio/managed-gitops pull request #480
Opened 2023-06-02 09:44 UTC by jparsai

## Description:
This PR is to refactor Environment E2E tests and remove TODO comment that is no longer required now.

## JIRA Story:
https://issues.redhat.com/browse/GITOPSRVCE-540
https://issues.redhat.com/browse/GITOPSRVCE-85

2023-06-02 20:40 UTC, keithchong approved these changes
@jparsai , LGTM.  From what I can tell, it is strictly refactoring.

2023-06-09 22:22 UTC, jgwest requested changes

2023-06-09 22:22 UTC, jgwest commented on tests-e2e/core/managed_environment_test.go
> -package core
The goal of GITOPSRVCE-540 was actually only to move the `Environment E2E tests` part of this file, into `environment_test.go`. The remaining tests can thus stay within `managed_environment_test.go`.

The overall goal is:
- tests primarily for ManagedEnvironments go in `managed_environment_test.go`
- tests primarily for (AppStudio) Environment go in `environment_test.go`

2023-06-22 23:13 UTC, jgwest commented
Rebased to latest

2023-06-22 23:15 UTC, jgwest approved these changes
LGTM, thanks @jparsai, and thanks @keithchong for reviewing!

2023-06-27 02:08 UTC, merged