Add provisioned-by annotation to the DeploymentTarget
redhat-appstudio/managed-gitops pull request #482
Opened 2023-06-06 09:23 UTC by chetan-rns

#### Description:
- Add provisioned-by annotation to the DeploymentTarget indicating the name of the provisioner.
- Update unit and e2e tests

#### Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-579

2023-06-07 15:12 UTC, jopit approved these changes
lgtm

2023-06-08 15:17 UTC, jgwest requested changes
Looks great, thanks @chetan-rns! One question around where we want store the string constant, then good to go.

2023-06-08 15:17 UTC, jgwest commented on appstudio-controller/controllers/appstudio.redhat.com/devsandbox_deployment_controller.go
> +	annDynamicallyProvisioned = "provisioner.appstudio.redhat.com/provisioned-by"
Any objections to moving this field into `application-api` repo, so it can be consumed by other teams?

2023-06-22 22:24 UTC, jgwest commented
Thanks @chetan-rns! I've merged the application-api, so this PR is good to go once it's updated to reference application-api repo (and rebased to latest).

2023-06-28 22:12 UTC, jgwest approved these changes
Looks great, thanks again @chetan-rns, and thanks @jopit for reviewing!

2023-06-28 22:13 UTC, merged