Add display_name field to ClusterUser table in databse
redhat-appstudio/managed-gitops pull request #485
Opened 2023-06-07 11:00 UTC by Rizwana777

#### Description:
-  Added new field in cluster user table called display_name
- Removed `internalGetOrCreateClusterUserByNamespaceUID`  function as it implements same logic as `internalProcessMessage_GetOrCreateClusterUserByNamespaceUID`
- unit test

#### Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-600

2023-06-14 05:24 UTC, chetan-rns reviewed
Thanks, @Rizwana777. I've added a few Nit comments everything else looks good to me.

2023-06-14 05:24 UTC, chetan-rns commented on backend/eventloop/shared_resource_loop/sharedresourceloop.go
> +			clusterUser.Display_name = string(workspaceNamespace.Name)
`workspaceNamespace.Name` is already of type string. I don't think we need to explicitly convert it again.

2023-06-14 08:37 UTC, Rizwana777 commented
@chetan-rns Thanks for the review, Updated the chages

2023-06-14 12:13 UTC, chetan-rns approved these changes
Thanks  @Rizwana777 

/lgtm

2023-06-22 23:56 UTC, jgwest requested changes
Looks great @Rizwana777, and thanks @chetan-rns for reviewing! From me, just a quick test request then good to go.

2023-06-22 23:56 UTC, jgwest commented on backend-shared/db/clusteruser.go
> +
It seems like `UpdateClusterUser` isn't covered by unit tests, it couldn't hurt to add a quick test for this to improve coverage.

2023-06-28 22:15 UTC, jgwest approved these changes
Looks great, thanks again @Rizwana777, and thanks @chetan-rns for reviewing!

2023-06-28 22:15 UTC, merged