Add new database table ApplicationOwner
redhat-appstudio/managed-gitops pull request #489
Opened 2023-06-15 13:07 UTC by Rizwana777

#### Description:
- Added new database table - ApplicationOwner
- Unit tests

#### Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-602

2023-06-28 15:07 UTC, jopit commented on backend/eventloop/application_event_loop/application_event_runner_deployments.go
> +	if err := dbQueries.CreateApplicationOwner(ctx, &applicationOwner); err != nil {
Based on the discussion in standup, it's possible that the application owner row already exists, so the code should check for that and skip the creation in that case.

2023-06-30 10:25 UTC, Rizwana777 commented
@jopit thank you for reviewing PR, updated changes , PTAL

2023-07-17 08:56 UTC, jgwest requested changes
Looks great, thanks @Rizwana777 , and thanks @jopit  for reviewing!

Here are a couple items that came to mind while reviewing:
		
### 1) 

As with other with cases where we are adding new database tables to the DB, we should add a migration_test to `utilities/db-migration/migration_test`

### 2) 

This is one that should have been in the original story description, but I only remembered it as being necessary while reviewing another PR in the last sprint:

In 'cleanOrphanedEntriesfromTable_Application' in db_reconciler.go of 'backend' component, we are scanning through the database for any Application rows that are 'orphaned', that is, they are not referenced by a GitOpsDeployment (and thus the Application row should be deleted.)

When we find an Application row, to delete, we call `deleteDbEntry` on the Application. However, now that we have implemented ApplicationOwner, ApplicationOwner will have a foreign key to Application; this foreign key from ApplicationOwner to Application will prevent the Application from being deleted.

Thus, in 'cleanOrphanedEntriesfromTable_Application', we should find and delete the ApplicationOwner that points to the Application, before we delete the Application itself.

- We should also a unit test to `db_reconciler_test.go` that verifies this case: when an orphaned Application is deleted, we should make sure the ApplicationOwner is deleted as well.

2023-07-17 08:56 UTC, jgwest commented on backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
> +			By("Create new deployment.")
One more case I think we can test here:
1) Create a GitOpsDeployment/Application/ApplicationOwner like normal, like with the other tests in this file.
2) Delete the ApplicationOwner table, pointing to that Application.
3) Call 'applicationEventRunner_handleDeploymentModified()' and verify that ApplicationOwner is recreated

This is testing the update case: if we get a request for an Application, but the Application doesn't have an ApplicationOwner (for whatever reason), then we should make sure we create it. The code already does this, so it's just a matter of making sure we have a test case for this as well.

2023-07-17 08:56 UTC, jgwest commented on backend/eventloop/application_event_loop/application_event_runner_deployments_test.go
> +			Expect(err).ToNot(BeNil())
I think this one is still open to do.

2023-07-17 13:26 UTC, Rizwana777 commented
@jgwest thanks for the review, updated changes, PTAL

2023-07-17 13:26 UTC, Rizwana777 commented
@jgwest thanks for the review, updated changes, PTAL

2023-07-20 09:27 UTC, jgwest approved these changes
Looks perfect, thanks again @Rizwana777!

2023-07-21 10:19 UTC, merged