Copy operation state field from Application status
redhat-appstudio/managed-gitops pull request #492
Opened 2023-06-28 06:31 UTC by chetan-rns

#### Description:
- Add a new field `operationState` to the status of GitOpsDeployment CR
- Add a new field to store the operation state in the ApplicationState DB table
- Copy the operation state from Application to GitOpsDeployment
- Compress/Decompress the operation state before accessing it from the table
- Add unit tests and e2e tests

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-619

2023-06-28 07:04 UTC, chetan-rns commented
/retest

2023-07-05 16:23 UTC, jparsai commented
Hey @chetan-rns there are conflicts in PR, please resolve them, so that it is good for review.

2023-07-11 13:24 UTC, jparsai commented
/lgtm

2023-07-13 07:56 UTC, jgwest requested changes
Looks great, thanks @chetan-rns, and thanks for reviewing @jparsai! Some minor unit test changes that occurred to me during reviewing, then good to go.

2023-07-17 07:06 UTC, chetan-rns commented on backend-shared/db/types.go
> +	OperationState []byte `pg:"operation_state"`
Added the new field in db-migration test

2023-07-17 12:12 UTC, chetan-rns commented
@jgwest @jparsai I've added the missing tests. Also, I moved some common functions (compress/decompress) to backend-shared to avoid duplication. PTAL.

2023-07-17 19:03 UTC, jgwest approved these changes
Looks great, thanks again @chetan-rns!

2023-07-17 19:03 UTC, merged