Remove duplicates in e2e test files
redhat-appstudio/managed-gitops pull request #591
Opened 2023-08-03 06:27 UTC by Rizwana777

#### Description:
- (Provide a brief list of the changes you have made, and why you made those changes, if it is not obvious why)
- (You don't need to mention any changes/reasons which are already documented in the JIRA story)

#### Link to JIRA Story (if applicable):

2023-08-09 09:49 UTC, jgwest requested changes
Great work, this should make our E2E tests much easier to work with,  thanks @Rizwana777! A few more minor requests, then good to go.

2023-08-09 09:49 UTC, jgwest commented on tests-e2e/argocd/argocd_instance_test.go
> +			app := appFixture.BuildArgoCDApplication("argo-app-01", argocdNamespace, fixture.RepoURL, fixture.GitopsDeploymentPath, "HEAD", "", "", argocdv1.ClusterSecretName, destinationNamespace.Name, &appv
As above, for the calls to BuildArgoCDApplication, IMHO it's a bit more elegant in this case to leave it as a Go obj.

2023-08-09 09:49 UTC, jgwest commented on tests-e2e/argocd/argocd_appproject_test.go
> +			app = appFixture.BuildArgoCDApplication("argo-app-01", dbutil.GetGitOpsEngineSingleInstanceNamespace(), "", fixture.GitopsDeploymentPath, "HEAD", appProject.Name, "https://kubernetes.default.svc",
This is totally just my opinion :grin: , but IMHO I think the original was a bit easier to read (the `BuildArgoCDApplication` parameter list is fairly long, and it's not necessarily obvious which field corresponds to what)

2023-08-09 09:49 UTC, jgwest commented on tests-e2e/argocd/queryscoped_cluster_secrets_test.go
> +					argoCDApplication := application.BuildArgoCDApplication("test-"+userName, argoCDNamespace, "https://github.com/redhat-appstudio/managed-gitops/", fixture.GitopsDeploymentPath, "", "", "", "test-
As above, for the calls to BuildArgoCDApplication, IMHO it's a bit more elegant in this case to leave it as a Go obj.

2023-08-09 09:49 UTC, jgwest commented on tests-e2e/argocd/queryscoped_cluster_secrets_test.go
> +				// Attempt to deploy into a Namespace we don't have access to
As above, for the calls to BuildArgoCDApplication, IMHO it's a bit more elegant in this case to leave it as a Go obj.

2023-08-09 14:03 UTC, Rizwana777 commented
@jgwest Thank you for reviewing, addressed the comments, PTAl

2023-08-10 04:45 UTC, jgwest approved these changes
Looks great, thanks again @Rizwana777!

2023-08-10 04:45 UTC, merged