Add unit tests for Dispose* functions in backend-shared
redhat-appstudio/managed-gitops pull request #597
Opened 2023-08-09 12:43 UTC by Rizwana777

#### Description:

#### Link to JIRA Story (if applicable):
https://issues.redhat.com/browse/GITOPSRVCE-687

2023-08-17 05:21 UTC, chetan-rns reviewed
Looks good @Rizwana777. I suggest the following changes and I think it  applies to all the files:

1. We can skip the defer in `AfterEach` since there is only one statement in it.
2. Can we verify if the error returned when we try to get a resource after calling Dispose is for no rows found? We can probably use this existing utility function IsResultNotFoundError()

2023-08-17 07:31 UTC, Rizwana777 commented on backend-shared/db/gitopsengineinstance.go
> +		return 0, fmt.Errorf("error on deleting operation: %v\nPGError:%v\n ", err, pgErr)
This line is showing warning as `error strings should not end with punctuation or newlines (ST1005)` so I have added space at the end, now I removed \n at the end, please let me know if it is required

2023-08-19 20:48 UTC, jgwest requested changes
Looks great, thanks @Rizwana777! One final request: 

It looks like the inside of this block is not covered in DisposeResources/DisposeAppScopedResources:
```go
		disposeErr := resource.Dispose(ctx, dbq)
		if disposeErr != nil {
			if err == nil {
				err = disposeErr
			} else {
				// append the error to the existing error
				err = fmt.Errorf("error: %v. error: %v", disposeErr, err)
			}
		}
```

It should be possible to cover these by creating a mock resource that implements the DisposableResource interface, but have the 'Dispose' function of that interface return an error.

2023-08-22 22:29 UTC, jgwest commented
fail on must-gather

/retest

2023-08-23 07:29 UTC, Rizwana777 commented
/test managed-gitops-e2e-tests

2023-08-23 10:01 UTC, merged