Remove secret_controller and test; Use EnqueueRequestsFromMapFunc (#670)
redhat-appstudio/managed-gitops pull request #604
Opened 2023-08-14 05:59 UTC by keithchong

#### Description:
- The reasons for reconciliation of the managed environment appears to be changed in the Jira description, in that it no longer checks if the namespace matches.  If this is no longer required, we simply remove the if block (I kept it in)
- The construction of the Namespace in the original code seems incorrect, in that it uses namespace.name instead of namespace.namespace.  I did not change this behaviour, but if you think it should remain at namespace.name, then we should leave it.

#### Link to JIRA Story (if applicable):
- See https://issues.redhat.com/browse/GITOPSRVCE-560

2023-08-22 18:45 UTC, jgwest requested changes
Looks great, thanks @keithchong! A minor tweak then good to go.

2023-08-22 18:45 UTC, jgwest commented on backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller_test.go
> +	//ctx := context.Background()
Can remove this if no longer needed

2023-08-24 21:17 UTC, keithchong commented on backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller_test.go
> +	//ctx := context.Background()
Done

2023-08-24 21:17 UTC, keithchong commented on backend/controllers/managed-gitops/gitopsdeploymentmanagedenvironment_controller_test.go
> +				It("should return two managed environments", func() {
Done

2023-08-29 22:34 UTC, jgwest approved these changes
LGTM, thanks @keithchong! And thanks for your patience in getting this approved :+1:

2023-08-29 22:34 UTC, merged