Store the full contents of Application status in a single DB field
redhat-appstudio/managed-gitops pull request #640
Opened 2023-09-07 14:16 UTC by chetan-rns

#### Description:
- Introduce a single status field in the ApplicationState DB
- Remove the individual status fields from the ApplicationState DB
- Update the backend and cluster agent to process the single status field

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-738

2023-09-23 09:48 UTC, jgwest requested changes
Looks great, very nice, thanks @chetan-rns! Just a minor tweak to the upgrade schema then should be good to go.

2023-09-23 09:48 UTC, jgwest commented on backend-shared/util/fauxargocd/faux_argo_cd.go
> +// TODO: describe members of this type
Let's remove this TODO: it's from the original Argo CD file upon which this part of the PR is based (I'm sure they'll get around to doing it any day now :grin: )

2023-10-03 09:06 UTC, chetan-rns commented on utilities/db-migration/migrations/000020_v20.down.sql
> +ALTER TABLE ApplicationState ADD COLUMN health VARCHAR (30) NOT NULL;
Sorry for delaying this. You are correct. I was able to reproduce the issue:

```
Unable to migrate database: unable to downgrade migration version by 1 level: migration failed: column "health" of relation "applicationstate" contains null values in line 0: ALTER TABLE ApplicationState DROP COLUMN argocd_application_status;
```

Adding a Default as 'Unknown' will fix the error.

2023-10-04 16:52 UTC, jgwest commented
Rebased to latest from `main`

2023-10-06 15:32 UTC, jgwest approved these changes
LGTM, thanks again @chetan-rns!

2023-10-06 15:32 UTC, merged