Add additional DB unit tests
redhat-appstudio/managed-gitops pull request #689
Opened 2023-10-20 12:06 UTC by chetan-rns

#### Description:
- Add additional unit tests for DB Queries

#### Link to JIRA Story (if applicable):

https://issues.redhat.com/browse/GITOPSRVCE-693

2023-10-25 18:30 UTC, jopit requested changes
Looks good, just one very minor change.

2023-10-25 18:30 UTC, jopit commented on backend-shared/db/app_project_repository_test.go
> +		It("should return an error if the cluster user ID ID field is not set", func() {
`ID` is duplicated.

2023-10-26 07:25 UTC, chetan-rns commented
/retest

2023-10-26 12:08 UTC, jopit approved these changes
lgtm

2023-10-26 13:33 UTC, jgwest approved these changes
LGTM too, thanks @chetan-rns, and thanks @jopit for reviewing!

2023-10-26 13:33 UTC, merged