Add database unit tests
redhat-appstudio/managed-gitops pull request #74
Opened 2022-03-04 15:19 UTC by raghavi101

This PR :

Adds unit tests (<file_name>_test.go) for the following db files located in backend-shared/config/db 
- managedenvironment.go
- kubernetesresourcetodbresourcemapping.go
- gitopsengineinstance.go

It is a part of [GITOPSRVCE-100](https://issues.redhat.com/browse/GITOPSRVCE-100)

Needs debugging : 
```
Error Trace:    kubernetesresourcetodbresourcemapping_test.go:103
                Error:          Received unexpected error:
                                error on deleting operation: pg: model=KubernetesToDBResourceMapping does not have primary keys
```

2022-03-08 11:07 UTC, jgwest requested changes
Looks great, thanks @raghava101!

I have pushed a fix to your branch re:  the errors you were seeing (the pointer one, and the primary key one). You will need to do `git pull` on your branch to pick up the changes.

A few items that jumped out at me as I was reviewing:

#### 1) As I was reviewing, I realized an additional thing that we should test:
- In the Get test, call Get with a primary key that doesn't exist: ensure that an error is returned, and that the IsResultNotFoundError(error) is true.
- Replace assert.Equal with assert.ObjectsAreEqualValues, when comparing the before and after calls of a get method 

I've added this to the story criteria of the story. We should do this for all the `Get*` functions in the PR.


#### 2) Also: 

Can you add new code to testSetup(), that will delete any KubernetesResourceToDBResourceMapping DB table entries that have a primary key that begins with "test-"?

In order to implement this, you may need to add a new 'UnsafeListAllKubernetesResourceToDBResourceMapping' function (see similar UnsafeListAll) examples in the code for details.

2022-03-08 11:10 UTC, jgwest commented
FYI @raghavi101 On another PR, I switched the code to require Go 1.17, so you may need to:
- update your system's Go version to 1.17
- rebase your branch onto the main branch
- run `go mod tidy` on backend-shared
- push any updates to the PR

2022-03-08 11:37 UTC, jgwest requested changes

2022-03-08 11:39 UTC, jgwest commented on backend-shared/config/db/gitopsengineinstance_test.go
> +	assert.Equal(t, gitopsEngineInstanceput.Namespace_name, gitopsEngineInstanceget.Namespace_name)
As above, should do assert.Equal on the full object.

2022-03-08 11:40 UTC, jgwest commented on backend-shared/config/db/kubernetesresourcetodbresourcemapping_test.go
> +	assert.Equal(t, kubernetesToDBResourceMappingpost.KubernetesResourceUID, kubernetesToDBResourceMappingget.KubernetesResourceUID)
As above.

2022-03-08 11:41 UTC, jgwest commented on backend-shared/config/db/managedenvironment_test.go
> +	assert.Equal(t, managedEnvironment.Name, getmanagedEnvironment.Name)
As above, should compare full object.

2022-03-09 08:28 UTC, raghavi101 commented
Thanks Jonathan for your review! Committed all the changes that were pointed out in the comments. PTAL

2022-03-10 11:03 UTC, jgwest requested changes
Looks great, just one more tweak (add an `assert` across a few methods) then good to go.

Oh and make sure you do this, so that the PR checks start passing: https://github.com/redhat-appstudio/managed-gitops/pull/74#issuecomment-1061664270

2022-03-10 11:03 UTC, jgwest commented on backend-shared/config/db/managedenvironment_test.go
> +		if !IsResultNotFoundError(err) {
Asserts as above.

2022-03-10 12:53 UTC, raghavi101 commented
Done, pushed requested changes. (Glad the checks passed, thanks Jonathan!)

2022-03-11 08:46 UTC, samyak-jn reviewed
Hi!
I was going through the PR and on the first quick look I found out a `.DS_Store` file is also committed to it, I suspect it might be a result of doing `git add .` or is it expected? If not, clear the file from the PR.

2022-03-11 09:31 UTC, raghavi101 commented
Hi Samyak! Thanks, I made the reviewed changes

2022-03-14 11:46 UTC, jgwest requested changes
Looks like we need to update a number of the`if assert.True(` calls: the `assert.*` functions return true  on success, so we should only return on failure of these statements.

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/gitopsengineinstance_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
This should be `if !assert.True(`, I believe.

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/gitopsengineinstance_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/gitopsengineinstance_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/gitopsengineinstance_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/kubernetesresourcetodbresourcemapping_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/managedenvironment_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/managedenvironment_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-14 11:46 UTC, jgwest commented on backend-shared/config/db/managedenvironment_test.go
> +	if assert.True(t, IsResultNotFoundError(err)) {
Should be `if !assert.True(`

2022-03-15 11:07 UTC, merged